substitutions:
  _SERVICE: 'backend-live-server'
  _REGION: 'europe-west3'

steps:
  - name: 'node:20'
    entrypoint: 'bash'
    args: ['-c', 'npm ci']

  - name: 'node:20'
    entrypoint: 'bash'
    args: ['-c', 'npx nx build backend-live-server --configuration=production']

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/backend-live-server:$SHORT_SHA',
        '-f',
        'apps/backend-live-server/Dockerfile',
        '.',
      ]

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/backend-live-server:$SHORT_SHA']

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - -c
      - |
        gcloud run deploy ${_SERVICE} \
          --image gcr.io/$PROJECT_ID/backend-live-server:$SHORT_SHA \
          --region ${_REGION} \
          --platform managed \
          --allow-unauthenticated \
          --set-secrets FIREBASE_PRIVATE_KEY=FIREBASE_PRIVATE_KEY:latest,GOOGLE_API_KEY=GOOGLE_API_KEY:latest \
          --set-env-vars GOOGLE_CLOUD_PROJECT=YOUR-PROJECT-ID,GOOGLE_CLOUD_LOCATION=us-central1,GOOGLE_GENAI_USE_VERTEXAI=false,FIREBASE_PROJECT_ID=YOUR-PROJECT-ID,FIREBASE_CLIENT_EMAIL=YOUR-CLIENT-EMAIL

images:
  - 'gcr.io/$PROJECT_ID/backend-live-server:$SHORT_SHA'

timeout: '1600s'

options:
  logging: CLOUD_LOGGING_ONLY
